server:
  port: 21507
spring:
  datasource:
    url: jdbc:mysql://mysqleb40272bc181.rds.ivolces.com:3306/matrix-connect-dev?serverTimezone =Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: matrix-connect-dev
    password: matrix-connect-dev@123!
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  file:
    path: /home/lizhenjie/logs/
  config: classpath:logback-dev.xml
  level:
    cn.qfei.connect.mapper: debug

crm:
  active : dev
  enable-log: true
  retry-times: 3
  connect-timeout: 1000*60*3


data:
  config:
    uri: https://devconnector-matrix.qfei.cn/




