server:
  port: 21507
  servlet:
    context-path: /api/matrix-connect
spring:
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: matrix-connect
  jackson:
    serialization:
      write_dates_as_timestamps: true
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    banner: false
    enable-sql-runner: true
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: DELETE_FLAG
      logic-delete-value: DELETED
      logic-not-delete-value: NOT_DELETE
    mapper-locations: classpath*:mapper/*.xml
    type-handlers-package: com.test.common.handler
    pagination:
      type: OFFSET
