server:
  port: 21507
spring:
  datasource:
    url: jdbc:mysql://mysql637ce7140f5e.rds.ivolces.com:3306/matrix-connect-line?serverTimezone =Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: matrix-connect
    password: matrix-connect@123!
    type: com.zaxxer.hikari.HikariDataSource

logging:
  file:
    path: /home/lizhenjie/logs/
  config: classpath:logback-dev.xml
  level:
    cn.qfei.connect.mapper: debug


crm:
  active : prod
  enable-log: true
  retry-times: 3
  connect-timeout: 1000*60*3

data:
  config:
    uri: https://matrix.qfei.cn/login?key=zhishu/