server:
  port: 21507
spring:
  datasource:
    url: jdbc:mysql://mysqleb40272bc181.rds.ivolces.com:3306/matrix-connect-dev?serverTimezone =Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: matrix-connect-dev
    password: matrix-connect-dev@123!
    type: com.zaxxer.hikari.HikariDataSource

logging:
  file:
    path: /home/lizhenjie/logs/
  config: classpath:logback-dev.xml
  level:
    cn.qfei.connect.mapper: debug

crm:
  active : local
  enable-log: true
  retry-times: 3
  connect-timeout: 1000*60*3


data:
  config:
    uri: https://1ce8d95a-889e-4bcb-8dc7-89ac630670d6-00-3a9udkug0khjc.sisko.replit.dev/